services:
  dat:
    build:
      context: .
    image: trixie-slim:uv-nvm
    container_name: dat
    working_dir: /root/dat
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/dat
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    ipc: host
    tty: true

  dat-gpu:
    extends:
      service: dat
    container_name: dat-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu